//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""General"",
            ""id"": ""5a4f6f2a-2946-43b5-8ade-aa9100909025"",
            ""actions"": [
                {
                    ""name"": ""ButtonSouth"",
                    ""type"": ""Button"",
                    ""id"": ""56fa6a70-b72a-4540-961e-996a5557686c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonEast"",
                    ""type"": ""Button"",
                    ""id"": ""5f6e18ad-0d88-4572-88fc-a9a5429447d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonWest"",
                    ""type"": ""Button"",
                    ""id"": ""f0a47052-92a9-47a6-9e8a-b614843cd62c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonNorth"",
                    ""type"": ""Button"",
                    ""id"": ""afe59637-4216-4434-a699-f6d0e80d0b39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShoulderLeft"",
                    ""type"": ""Button"",
                    ""id"": ""b5b6484d-ace6-4824-b6af-3b800635b8a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShoulderRight"",
                    ""type"": ""Button"",
                    ""id"": ""cc4010b8-0b92-4a80-ab05-83f2d918e086"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""28ea2e4b-21fe-486a-bb7e-4934db90b978"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""dc06dd1b-6288-4fd2-829c-a7f04be9613d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""3d2effaf-a43f-45a0-8874-9741e7cdf968"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cf175a6f-0813-442a-bf56-f32c46de1c1b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ButtonSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68ade266-bdad-4453-9591-7aad715f1b0a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""478b3cc7-dd32-462f-9650-ae1aa0482c9c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ButtonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc9a8182-37cf-4732-bc10-2bae07b7e480"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ButtonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e0671a4-a101-49e9-a171-bff0e3a4e395"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ButtonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e40dfc07-7bb2-4875-9383-d10388e11b41"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ShoulderLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dec57a1a-11f4-4758-ad7e-3ee25af319c6"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ShoulderRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d47d0a10-ff03-41f7-9b54-eca5bb362fb4"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""b04438a2-82d7-4384-8a77-3a2d1c8b46d4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""be3aa536-921a-49bf-8436-a0222731f0a4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f5e0bde3-e346-412e-aede-19bc90e37582"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6d869e59-76d6-4382-925a-d704380a7023"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""21788f73-e77c-4255-a31d-c7e805a94fcb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""18cf853c-e490-410d-a309-ee26c25de312"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc8eed1a-4403-4217-b6ab-74eba7f103d0"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddf959d2-0200-425f-862c-89610ae1ef30"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShoulderLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2be98bb-6a9a-4a83-bf02-fcc79bd21659"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShoulderRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbb3bafc-8dfe-4b71-888a-c8c95882ce0b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Pause"",
            ""id"": ""45839283-ac48-4dd7-95f5-354c23bb6205"",
            ""actions"": [
                {
                    ""name"": ""PauseSouth"",
                    ""type"": ""Button"",
                    ""id"": ""23544a5a-db66-48f6-8635-ea43423016c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseEast"",
                    ""type"": ""Button"",
                    ""id"": ""5b094238-0b22-437c-b638-11ecb0276406"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseWest"",
                    ""type"": ""Button"",
                    ""id"": ""2d9bc5b2-dc24-4e3a-a291-976a3cc89a30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseNorth"",
                    ""type"": ""Button"",
                    ""id"": ""67210241-b789-413e-ab4f-c43d0c5752c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShoulderLeft"",
                    ""type"": ""Button"",
                    ""id"": ""7f9bcf60-160c-4bb7-8287-45e1ce855a56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShoulderRight"",
                    ""type"": ""Button"",
                    ""id"": ""6b8d248b-7b9a-4747-bf1e-db0250912b1c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""35ea441f-f0a7-4831-89c8-22986daefbc6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""4f69d30b-9dcd-4166-83b0-bad553ac351a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2ddb5482-be75-4a29-89af-a201e49086d9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""PauseSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5284329e-9422-4277-b35d-35f0271f90e0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43dbbdbc-e2f3-4168-a873-68b822d1f46a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""PauseEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06273d41-166f-4a3f-9210-c0d1f1d99319"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""PauseWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e93f22bc-beee-4d4d-8fe3-357d88fdcd7f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""PauseNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6118898e-eae3-4435-a8dd-e644a6a4b7b8"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ShoulderLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fa93e5a-312c-47be-a91f-d1abb95524a7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""ShoulderRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f7c8172-fe22-4e38-9db7-b21e22fcca36"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""08103d96-99ee-40ce-ae5f-212ad7e45755"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cb356a57-7d73-4fcf-bcb3-ec881b82e5d9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7dda7ff0-b293-48ce-9552-c0db8fc97696"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9c2ee5c8-597a-4910-a85e-fc1d5f974caf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""08506f08-c6fc-4d50-9280-5ae7f6dc7452"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e3566743-82ba-41c2-a133-3b475ea6e7be"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90c8b4a7-ec57-478d-86db-1bd36da85085"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7137c99-f7c2-4480-9096-2208de8f41b0"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShoulderLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""838399e8-64fd-43df-bcaa-1b4cc351e605"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShoulderRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_ButtonSouth = m_General.FindAction("ButtonSouth", throwIfNotFound: true);
        m_General_ButtonEast = m_General.FindAction("ButtonEast", throwIfNotFound: true);
        m_General_ButtonWest = m_General.FindAction("ButtonWest", throwIfNotFound: true);
        m_General_ButtonNorth = m_General.FindAction("ButtonNorth", throwIfNotFound: true);
        m_General_ShoulderLeft = m_General.FindAction("ShoulderLeft", throwIfNotFound: true);
        m_General_ShoulderRight = m_General.FindAction("ShoulderRight", throwIfNotFound: true);
        m_General_Movement = m_General.FindAction("Movement", throwIfNotFound: true);
        m_General_Left = m_General.FindAction("Left", throwIfNotFound: true);
        m_General_Start = m_General.FindAction("Start", throwIfNotFound: true);
        // Pause
        m_Pause = asset.FindActionMap("Pause", throwIfNotFound: true);
        m_Pause_PauseSouth = m_Pause.FindAction("PauseSouth", throwIfNotFound: true);
        m_Pause_PauseEast = m_Pause.FindAction("PauseEast", throwIfNotFound: true);
        m_Pause_PauseWest = m_Pause.FindAction("PauseWest", throwIfNotFound: true);
        m_Pause_PauseNorth = m_Pause.FindAction("PauseNorth", throwIfNotFound: true);
        m_Pause_ShoulderLeft = m_Pause.FindAction("ShoulderLeft", throwIfNotFound: true);
        m_Pause_ShoulderRight = m_Pause.FindAction("ShoulderRight", throwIfNotFound: true);
        m_Pause_Movement = m_Pause.FindAction("Movement", throwIfNotFound: true);
        m_Pause_Left = m_Pause.FindAction("Left", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General
    private readonly InputActionMap m_General;
    private IGeneralActions m_GeneralActionsCallbackInterface;
    private readonly InputAction m_General_ButtonSouth;
    private readonly InputAction m_General_ButtonEast;
    private readonly InputAction m_General_ButtonWest;
    private readonly InputAction m_General_ButtonNorth;
    private readonly InputAction m_General_ShoulderLeft;
    private readonly InputAction m_General_ShoulderRight;
    private readonly InputAction m_General_Movement;
    private readonly InputAction m_General_Left;
    private readonly InputAction m_General_Start;
    public struct GeneralActions
    {
        private @GameControls m_Wrapper;
        public GeneralActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ButtonSouth => m_Wrapper.m_General_ButtonSouth;
        public InputAction @ButtonEast => m_Wrapper.m_General_ButtonEast;
        public InputAction @ButtonWest => m_Wrapper.m_General_ButtonWest;
        public InputAction @ButtonNorth => m_Wrapper.m_General_ButtonNorth;
        public InputAction @ShoulderLeft => m_Wrapper.m_General_ShoulderLeft;
        public InputAction @ShoulderRight => m_Wrapper.m_General_ShoulderRight;
        public InputAction @Movement => m_Wrapper.m_General_Movement;
        public InputAction @Left => m_Wrapper.m_General_Left;
        public InputAction @Start => m_Wrapper.m_General_Start;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void SetCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterface != null)
            {
                @ButtonSouth.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonSouth;
                @ButtonSouth.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonSouth;
                @ButtonSouth.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonSouth;
                @ButtonEast.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonEast;
                @ButtonEast.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonEast;
                @ButtonEast.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonEast;
                @ButtonWest.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonWest;
                @ButtonWest.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonWest;
                @ButtonWest.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonWest;
                @ButtonNorth.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonNorth;
                @ButtonNorth.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonNorth;
                @ButtonNorth.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnButtonNorth;
                @ShoulderLeft.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnShoulderLeft;
                @ShoulderLeft.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnShoulderLeft;
                @ShoulderLeft.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnShoulderLeft;
                @ShoulderRight.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnShoulderRight;
                @ShoulderRight.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnShoulderRight;
                @ShoulderRight.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnShoulderRight;
                @Movement.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMovement;
                @Left.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnLeft;
                @Left.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnLeft;
                @Left.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnLeft;
                @Start.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnStart;
            }
            m_Wrapper.m_GeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ButtonSouth.started += instance.OnButtonSouth;
                @ButtonSouth.performed += instance.OnButtonSouth;
                @ButtonSouth.canceled += instance.OnButtonSouth;
                @ButtonEast.started += instance.OnButtonEast;
                @ButtonEast.performed += instance.OnButtonEast;
                @ButtonEast.canceled += instance.OnButtonEast;
                @ButtonWest.started += instance.OnButtonWest;
                @ButtonWest.performed += instance.OnButtonWest;
                @ButtonWest.canceled += instance.OnButtonWest;
                @ButtonNorth.started += instance.OnButtonNorth;
                @ButtonNorth.performed += instance.OnButtonNorth;
                @ButtonNorth.canceled += instance.OnButtonNorth;
                @ShoulderLeft.started += instance.OnShoulderLeft;
                @ShoulderLeft.performed += instance.OnShoulderLeft;
                @ShoulderLeft.canceled += instance.OnShoulderLeft;
                @ShoulderRight.started += instance.OnShoulderRight;
                @ShoulderRight.performed += instance.OnShoulderRight;
                @ShoulderRight.canceled += instance.OnShoulderRight;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Left.started += instance.OnLeft;
                @Left.performed += instance.OnLeft;
                @Left.canceled += instance.OnLeft;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
            }
        }
    }
    public GeneralActions @General => new GeneralActions(this);

    // Pause
    private readonly InputActionMap m_Pause;
    private IPauseActions m_PauseActionsCallbackInterface;
    private readonly InputAction m_Pause_PauseSouth;
    private readonly InputAction m_Pause_PauseEast;
    private readonly InputAction m_Pause_PauseWest;
    private readonly InputAction m_Pause_PauseNorth;
    private readonly InputAction m_Pause_ShoulderLeft;
    private readonly InputAction m_Pause_ShoulderRight;
    private readonly InputAction m_Pause_Movement;
    private readonly InputAction m_Pause_Left;
    public struct PauseActions
    {
        private @GameControls m_Wrapper;
        public PauseActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PauseSouth => m_Wrapper.m_Pause_PauseSouth;
        public InputAction @PauseEast => m_Wrapper.m_Pause_PauseEast;
        public InputAction @PauseWest => m_Wrapper.m_Pause_PauseWest;
        public InputAction @PauseNorth => m_Wrapper.m_Pause_PauseNorth;
        public InputAction @ShoulderLeft => m_Wrapper.m_Pause_ShoulderLeft;
        public InputAction @ShoulderRight => m_Wrapper.m_Pause_ShoulderRight;
        public InputAction @Movement => m_Wrapper.m_Pause_Movement;
        public InputAction @Left => m_Wrapper.m_Pause_Left;
        public InputActionMap Get() { return m_Wrapper.m_Pause; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseActions set) { return set.Get(); }
        public void SetCallbacks(IPauseActions instance)
        {
            if (m_Wrapper.m_PauseActionsCallbackInterface != null)
            {
                @PauseSouth.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseSouth;
                @PauseSouth.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseSouth;
                @PauseSouth.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseSouth;
                @PauseEast.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseEast;
                @PauseEast.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseEast;
                @PauseEast.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseEast;
                @PauseWest.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseWest;
                @PauseWest.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseWest;
                @PauseWest.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseWest;
                @PauseNorth.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseNorth;
                @PauseNorth.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseNorth;
                @PauseNorth.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnPauseNorth;
                @ShoulderLeft.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnShoulderLeft;
                @ShoulderLeft.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnShoulderLeft;
                @ShoulderLeft.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnShoulderLeft;
                @ShoulderRight.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnShoulderRight;
                @ShoulderRight.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnShoulderRight;
                @ShoulderRight.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnShoulderRight;
                @Movement.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnMovement;
                @Left.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnLeft;
                @Left.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnLeft;
                @Left.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnLeft;
            }
            m_Wrapper.m_PauseActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PauseSouth.started += instance.OnPauseSouth;
                @PauseSouth.performed += instance.OnPauseSouth;
                @PauseSouth.canceled += instance.OnPauseSouth;
                @PauseEast.started += instance.OnPauseEast;
                @PauseEast.performed += instance.OnPauseEast;
                @PauseEast.canceled += instance.OnPauseEast;
                @PauseWest.started += instance.OnPauseWest;
                @PauseWest.performed += instance.OnPauseWest;
                @PauseWest.canceled += instance.OnPauseWest;
                @PauseNorth.started += instance.OnPauseNorth;
                @PauseNorth.performed += instance.OnPauseNorth;
                @PauseNorth.canceled += instance.OnPauseNorth;
                @ShoulderLeft.started += instance.OnShoulderLeft;
                @ShoulderLeft.performed += instance.OnShoulderLeft;
                @ShoulderLeft.canceled += instance.OnShoulderLeft;
                @ShoulderRight.started += instance.OnShoulderRight;
                @ShoulderRight.performed += instance.OnShoulderRight;
                @ShoulderRight.canceled += instance.OnShoulderRight;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Left.started += instance.OnLeft;
                @Left.performed += instance.OnLeft;
                @Left.canceled += instance.OnLeft;
            }
        }
    }
    public PauseActions @Pause => new PauseActions(this);
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IGeneralActions
    {
        void OnButtonSouth(InputAction.CallbackContext context);
        void OnButtonEast(InputAction.CallbackContext context);
        void OnButtonWest(InputAction.CallbackContext context);
        void OnButtonNorth(InputAction.CallbackContext context);
        void OnShoulderLeft(InputAction.CallbackContext context);
        void OnShoulderRight(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
    }
    public interface IPauseActions
    {
        void OnPauseSouth(InputAction.CallbackContext context);
        void OnPauseEast(InputAction.CallbackContext context);
        void OnPauseWest(InputAction.CallbackContext context);
        void OnPauseNorth(InputAction.CallbackContext context);
        void OnShoulderLeft(InputAction.CallbackContext context);
        void OnShoulderRight(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
    }
}
